### ISSUE TITLE
TypeError: anvil_1.default is not a constructor

### ISSUE THREAD

**Issue by geekboy0801** [anvilco/node-anvil#43]
I tried to use node-anvil package in typescript based nestjs app. But this code gives an error in @anvilco/anvil, v2.8.1

```
import Anvil from '@anvilco/anvil';

// Initialize Node-anvil client
const anvilClient = new Anvil({
  apiKey: '----',
  baseURL: 'https://app.useanvil.com',
});

```

## Expected Behavior
It shouldn't throw errors

## Actual Behavior
```
const anvilClient = new anvil_1.default({
                    ^

TypeError: anvil_1.default is not a constructor
    at Object.<anonymous> (F:\sydecar\backend\dist\esign\esign.service.js:13:21)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (F:\sydecar\backend\dist\esign\esign.module.js:11:25)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
                                                                                 
```

**Comment by geekboy0801** [comment]
```
import * as Anvil from '@anvilco/anvil';
```

This solved the problem.
